kind: ConfigMap
apiVersion: v1
metadata:
  name: template-maps
  namespace: receipts
data:
  MARKDOWN_DEBTOR: "È stato effettuato il pagamento di un avviso intestato a te:\n\n**Importo**: {transaction.amount} €\n\n**Oggetto:** {cart.items[0].subject}\n\n**Ente creditore**: {cart.items[0].payee.name}\n\nEcco la ricevuta con i dettagli."
  SUBJECT_DEBTOR: "Ricevuta del pagamento a {cart.items[0].payee.name}"
  MARKDOWN_PAYER: "Hai effettuato il pagamento di un avviso:\n\n**Importo**: {transaction.amount} €\n\n**Oggetto:** {cart.items[0].subject}\n\n**Ente creditore**: {cart.items[0].payee.name}\n\nEcco la ricevuta con i dettagli."
  SUBJECT_PAYER: "Ricevuta del pagamento a {cart.items[0].payee.name}"
